### ISSUE TITLE
your app for fdroid

### ISSUE THREAD

**Issue by theScrabi** [pflammertsma/cryptogram#11]
Hello,

as krt shew already over at the [fdroid](https://f-droid.org/forums/topic/cryptogram/) submit, you'd have to fix serveral issues about your app in order to get it into fdroid.

Here they are:
- get rid of [any gsm libs](https://github.com/pflammertsma/cryptogram/blob/master/app/build.gradle#L103)
- get rid of [crashanalytics](https://github.com/pflammertsma/cryptogram/blob/master/app/build.gradle#L126)
- get rid of [non trusted maven repos](https://github.com/pflammertsma/cryptogram/blob/master/app/build.gradle#L88)

You can achieve the last one by using source code instead of the maven packages:
- [easy-video-player](https://github.com/afollestad/easy-video-player)
- [gene-rate](https://github.com/Pixplicity/gene-rate)
- [easyprefs](https://github.com/Pixplicity/EasyPreferences)
- [easy-video-player](https://github.com/afollestad/easy-video-player) but that should also be available via jCenter
- [material dialogs](https://github.com/afollestad/material-dialogs)

If you don't want to change this on the master branch, you can still create a fdroid branch, where you fix fdroid related issues.

rgds Schabi

**Comment by pflammertsma** [comment]
I really appreciate the amount of effort you've given into researching this. The amount of maintenance this would introduce is unfortunately restrictive for this hobby project, I'm afraid. I understand there are users that prefer having proper, completely open-source apps.

Furthermore, pulling in all code directly from the sources and dropping support for things like Crashlytics and Google Play Services would inhibit me from observing crashes and ultimately would give a poor user experience as I would have no way of knowing when the app falters.

For that reason, I'm electing to leave fdroid integration to another enthusiast. Thank you again for your detailed message, Schabi.
