### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Sv443** [pflammertsma/cryptogram#62]
If you need a German translation, I'll be willing to do it. Unfortunately I know nothing about Android app programming, else I'd have forked it but if you tell me how to do it, I will.

**Comment by Sv443** [comment]
Is it just the cryptograms.json file in app/src/main/assets?

**Comment by pflammertsma** [comment]
Yes, but those are only the puzzles. Unfortunately in the current form, there's not really and internationalization support for puzzles.

What do you think about having completely different set of quotes per language, as some quotes might not carry over well? I'm open to suggestions.

For now, perhaps take a copy of `cryptograms.json` and place it in a subdirectory:

    app/src/main/assets/de

I can then perhaps begin partitioning the puzzles by language, allowing users to select a language (while defaulting to the device locale).

**Comment by pflammertsma** [comment]
As for the UI strings, these can be found as per Android convention, under `app/src/main/res/strings.xml`.

**Comment by pflammertsma** [comment]
Thanks for willing to invest your time into this and in advance for your contributions!

**Comment by Sv443** [comment]
Yes, I think different quotes would be the best way to translate it. I will definetely take a look at the source code and translate it :)

**Comment by pflammertsma** [comment]
Awesome that you're up for the challenge!

Yes, those are the two files. Currently there is no support for i10n of the json file; I can create a branch with this functionality for you to continue in, if that's useful.

**Comment by Sv443** [comment]
Yes, that would be nice.

**Comment by pflammertsma** [comment]
Please see `feature/puzzle-i10n`. I've created a placeholder json file for German puzzles; feel free to replace it.

Note that progress isn't handled correctly when switching languages. Puzzles are often reset as a consequence.

**Comment by Sv443** [comment]
I'm sorry to tell you this but my life has changed very much and I sadly don't have any free time to do this like I had in September 2018 anymore. Though if the times change and I have more free time I will try to continue with it.

**Comment by pflammertsma** [comment]
Absolutely no problem, @Sv443. All the best, and thanks for reaching out.
