### ISSUE TITLE
option- how to add "new line"(/n) to texts -for conversational texts 

### ISSUE THREAD

**Issue by moslem7342** [pflammertsma/cryptogram#81]
This option is used in texts that are conversational

**Comment by pflammertsma** [comment]
I'm not sure what you are referring to; Cryptogram doesn't have a notion of "conversational texts."

**Comment by moslem7342** [comment]
ex : A dialogue from a movie 
i want to add "new line" in end of each line

**Comment by pflammertsma** [comment]
Thanks for the feedback. I'm not sure if I'm fully understanding, but to be clear, are you expecting to be able to alter the text of the puzzle? The goal is to resolve the concealed text, and there is no mechanism in the game to alter the content of the puzzle itself.

Note that you can extract the content of the puzzle after solving it by sharing, however.
