### ISSUE TITLE
Customization of background colors, esp. inversed for nighttime playing

### ISSUE THREAD

**Issue by pflammertsma** [pflammertsma/cryptogram#9]

**Comment by Thunderbottom** [comment]
Implemented in #10, please take a look.

Also, an advice to not upload your [Crashalytics API key](https://github.com/pflammertsma/cryptogram/blob/master/app/src/main/AndroidManifest.xml#L36), it can be misused.

**Comment by pflammertsma** [comment]
Thanks so much! It's been merged and deployed.
